name: component tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  component-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        run: npm install && npm run build

      - name: Run component tests
        uses: cypress-io/github-action@v6
        with:
          component: true
